version: '3.3'

services:
  food-delivery-backend:
    image: ${BACKEND_IMAGE}
    ports:
      - '5000:5000'
    environment:
      - CI=true
      - DB_HOST=food-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=BUILD
    restart: always
  food-db:
    image: postgres:latest
    container_name: pgcontainer
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: