INSERT INTO "Restaurant" (name) VALUES ('Meal Mate');

INSERT INTO "Section" (name, restaurant_id) VALUES ('Italian', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Chinese', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Mexican', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Indian', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('French', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Japanese', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Thai', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Greek', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Spanish', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Vietnamese', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Turkish', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Moroccan', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Caribbean', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Ethiopian', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Brazilian', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('German', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Mediterranean', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Lebanese', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Persian', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Russian', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('American', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('British', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Cuban', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Filipino', 1);
INSERT INTO "Section" (name, restaurant_id) VALUES ('Beverages', 1);

INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Margherita Pizza', 'https://foodbyjonister.com/wp-content/uploads/2020/01/MargheritaPizza.jpg', 1, 8.99, 'mozzarella, tomatoes, basil, olive oil');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Pepperoni Pizza', 'https://www.simplyrecipes.com/thmb/KE6iMblr3R2Db6oE8HdyVsFSj2A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__09__easy-pepperoni-pizza-lead-3-1024x682-583b275444104ef189d693a64df625da.jpg', 1, 9.99, 'pepperoni, mozzarella, tomato sauce, oregano');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Caesar Salad', 'https://lindseyeatsla.com/wp-content/uploads/2021/10/Lindseyeats_Classic_Caesar_Salad-2.jpg', 1, 7.99, 'romaine lettuce, Caesar dressing, croutons, Parmesan cheese');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Grilled Chicken Sandwich', 'https://static.toiimg.com/thumb/54734028.cms?imgsize=73275&width=800&height=800', 21, 10.99, 'grilled chicken, lettuce, tomato, mayo, sandwich bun');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Spaghetti Carbonara', 'https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-square640-v2.jpg', 1, 12.99, 'spaghetti, eggs, cheese, pancetta, black pepper');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Cheeseburger', 'https://static01.nyt.com/images/2023/07/13/multimedia/13xp-cheese-king/13xp-cheese-king-superJumbo.jpg', 21, 11.99, 'beef patty, cheddar cheese, lettuce, tomato, onion, burger bun');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Fish Tacos', 'https://www.howsweeteats.com/wp-content/uploads/2023/08/grilled-fish-tacos-17.jpg', 3, 9.99, 'fish fillets, cabbage slaw, lime crema, salsa, tortillas');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Chocolate Cake', 'https://sallysbakingaddiction.com/wp-content/uploads/2013/04/triple-chocolate-cake-4.jpg', 4, 6.99, 'flour, cocoa powder, sugar, eggs, butter, chocolate');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Tiramisu', 'https://bakeplaysmile.com/wp-content/uploads/2022/06/tiramisu-square-500x500.jpg', 1, 7.99, 'ladyfingers, coffee, mascarpone cheese, cocoa powder');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Espresso', 'https://www.seriouseats.com/thmb/MS_5p-UVwIHCrr5MaXonYJajP7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2018__06__20180613-coffee-vs-espresso-vicky-wasik-3-1500x1125-418fa2a14e7249b18040c2c34bf8569c.jpg', 25, 2.99, 'espresso beans, water');
INSERT INTO "Product" (name, image, section_id, price, ingredients) VALUES ('Lemonade', 'https://i2.wp.com/lmld.org/wp-content/uploads/2022/04/Lemonade-4.jpg', 25, 3.99, 'lemons, sugar, water');
